---
title: "Visualizing Raster Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizing Raster Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Workspace setup

```{r prettymaps setup, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(leaflet)
library(tidyterra)
library(ggspatial)
library(ggsn)
library(ggplot2)
library(gridExtra)
library(rSDP)
```

## Finding SDP data

```{r find data}
snow_cat <- sdp_get_catalog(domains="UG",types="Snow",releases="Release4")
snow_cat[,c(1,4)]
```

## Reading in data

```{r get data}
snow_rast <- sdp_get_raster("R4D001",years=2018:2021,
                            download_files = TRUE, download_path = "~/Downloads")
roads <- st_read("https://rmbl-sdp.s3.us-east-2.amazonaws.com/data_products/supplemental/UG_roads_trails_osm.geojson")
```
## Formatting data

```{r format data}
##Pulls out major roads.
roads_major <- filter(roads,highway %in% c("secondary","trunk"))

##Converts to spatvector.
roads_sv <- vect(roads_major)

##Re-projects to coordinate system of raster.
roads_proj <- project(roads_sv,crs(snow_rast))
```

## Basic raster maps with `terra::plot()`

```{r terra plot}
jet_colors <-
  colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

plot(snow_rast[[1]],range=c(25,220),nc=3,
     col=rev(jet_colors(255)),
     main="Snow Persistence (Day of Year)")
plot(roads_proj,add=TRUE,col="grey20")
```

## Web maps with leaflet

```{r terra plet,out.width="100%"}
map <- terra::plet(snow_rast[[1]],tiles="Streets",col=jet_colors(255))
lines(map,roads_proj,col="white")
```
## Prettier maps with tidyterra and ggplot2

```{r tidyterra basic, out.width="6in"}
## Simple one-panel map.
map0 <- ggplot()+
  geom_spatraster(data=snow_rast[[1]])+
  geom_spatvector(aes(color="highway"),data=roads_proj)+
  scale_color_manual("",values=c("grey40"))+
  scale_fill_whitebox_c("Day of Year",limits=c(20,220),
                        palette="muted",direction=1)+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme_minimal()

## Adding a scale bar and north arrow.
map0 + 
  annotation_scale(location="br", height=unit(0.2,"cm"))+
  annotation_north_arrow(location="bl", height=unit(1,"cm"))
```

```{r map zoom, warning=FALSE, message=FALSE}
## Zooming in.
map0 + scale_x_continuous(limits=c(327306.007419024, 342195.337294167),expand=c(0,0))+
       scale_y_continuous(limits=c(4289070.14096146, 4307572.32293866),expand=c(0,0))
```

## Faceting for multi-panel maps

### Simple faceted map
```{r tidyterra facets}
map1 <- ggplot()+
  geom_spatraster(data=snow_rast[[1:3]])+
  facet_wrap(facets=~lyr)+
  theme_minimal()
map1
```

### Full faceted map with scalebar
```{r full}

# North Arrow and Scale Bar properties.
arrow_params <- tibble::tibble(
  lyr = "2020",
  location = "br")

scale_params <- tibble::tibble(
  lyr = "2018",
  location= "br",
  width_hint=0.2)

# Full Map
map2 <- ggplot()+
  geom_spatraster(data=snow_rast[[1:3]],maxcell=5e+04)+
  geom_spatvector(aes(color="highway"),data=roads_sv)+
  labs(title="Spring Snow Persistence",tag="(a)")+
  scale_fill_whitebox_c("Day of Year",palette="muted",direction=1,limits=c(20,220))+
  scale_color_manual("",values=c("grey40"))+
  scale_x_continuous(expand=c(0,0),breaks=c(-107,-106.4))+
  scale_y_continuous(expand=c(0,0),breaks=c(38.5,38.7,38.9))+
  annotation_north_arrow(aes(location=location),
                         style=north_arrow_minimal(),
                         which_north="true",
                         data=arrow_params)+
  annotation_scale(aes(location=location,
                   width_hint=width_hint),
                   style="ticks",
                   data=scale_params)+
  facet_wrap(~lyr,ncol=4)+
  theme_minimal()+
  theme(axis.text.x=element_text(size=10),
        axis.text.y=element_text(size=10))
print(map2)
```
## Exporting maps

### PNG Export
```{r export png}
png("~/Downloads/snow_3panel_tidyterra.png",
    width=800,height=450,units="px")
map2
dev.off()
```

### PDF Export
```{r export}
pdf("~/Downloads/snow_3panel_tidyterra.pdf",
    width=8,height=4.5)
map2
dev.off()
```
